export const constant = {
    apiEndPoint:{
        EDITMYACCOUNT: 'User_router/update_user',
        GETCLIENT: 'client/get_all_clients',
        ADDUSER: 'User_router/create_user',
        ADDNOTIFICATION: 'notification/addnotification',
        UPDATENOTIFICATION:'notification/updatenotification',
        UPDATEMASTERS:'update_masters',
        ADDPARTNER: 'User_router/create_user',
        CHANGEPASSWORD: 'User_router/change__password',
        CHANGEPROFILEIMAGE: 'User_router/change-image',
        LOGIN: 'auth/login',
        FORGOTPASSWORD: 'auth/forget_possword',
        SENDTOKEN: 'auth/sendToken',
        RESTPASSWORD: 'auth/reset_password',
        ADDCLIENT: 'client/insert_client',
        EDITCLIENT: 'client/update_client',
        ADDMANUALCANDIDATE: 'candidate/insert_manual_candidate',
        EDITCANDIDATE: 'candidate/edit_candidate',
        UPDATECANDIDATESTAGE: 'candidate/update_candidate_stage',
        ADDEANDI: 'eandi/insert_eandi',
        REASSIGNRECRUTER: 'indent/add_recruiter',
        REASSIGNPARTNER: 'indent/add_partner',
        REGISTER: 'auth/register',
        ADDEANDIQUESTION: 'eandi/create_eandi_question',
        EANDITEST: 'eandi/create_eandi_submit',
        EANDITEST2: 'eandi/create_eandi_submit2',
        UPDATEINDENTSTATUS: 'indent/update_indent_status',
        ADDINSERTEANDI: 'master/insert_master_data',
        GETPARTNER: 'partner/get_partner',
        INSERTPARTNER: 'partner/add_partner',
        EDITPARTNER: 'partner/update_partner',
        GETUSERCANDIDATE: 'candidate/get_candidate_from_userId',
        RESUMEEXTRACT: 'candidate/resume',
        APPALYINDENT: 'candidate/generate_indent_score',
        VERIFYEMAIL: 'auth/verify_registration',
        GETSINGLEPARTNER: 'partner/get_single_partner',
        SINGLERESUME: 'candidate/upload_single_resume',
        SAVESINGLECANDIDATE: 'candidate/save_single_candidate',
        INSERTEANDIQUESTION: 'eandi/addeandiQuestion',
        ADDASSESSMENT: 'Assessment/insert_assessment',
        INSERTASSESSMENTQUESTION: 'Assessment/addassessmentQuestion',
        ASSESSMENTTEST: 'Assessment/assessment_test',
        ADDPROCESS:'addprocess',
        CHECKDUPLICATE: 'auth/check_duplicate',
        DCATOINDENT: 'candidate/apply_to_indent',
        UPDATEPARTNERSTAGE: 'partner/approve_partner2',
        GENACCESSTOKEN: 'auth/gen_access_token',
        UPDATEINDENT:'indent/update_indent',
        SAVEASDRAFTCANDIDATE: 'candidate/save_as_draft',
        EDITPARTNER2: 'partner/update_partner2',
        CLIENTLIST: 'master/get_all_clients_list',
        RECRUITERLIST: 'User_router/get_all_recruiter_list',
        PARTNERLIST: 'partner/get_all_partner_list',
        UPDATEEANDIQUESTIONS: 'eandi/editeandiQuestion',
        UPDATECITY:'master/insert_new_city_data',
        GETJOBCODE:'master/gen_job_code_id',
        CLONEENI:'eandi/create_eandi_clone',
        GETLOCATION: 'indent/get_indent_location_status',
        UPDATELOCATIONSTATUS: 'indent/update_indent_location_status',
        UPDATEEANDI: 'eandi/update_eandi',
        APPLYEXISTCANDIDATESENI: 'eandi/apply_exist_candidates_eandi_test',
        APPLYEXISTCANDIDATEAISCORE: 'eandi/apply_exist_candidates_AI_score',
        UPDATENOTIFICATIONVIEWSTATUS: 'web_notifications/update_view_status',
        UPDATECVUPLOADURL: 'master/update_config_master_data',
        FETCHTEMPLATEVAR:'notification/fetch_tem_variables',
        SENDBULKNOTIFICATION: 'partner/send_bulk_notifications',
        SINGLEINDENT: 'indent/get_indent_details',
    }
}